networks:
  monitoring:
    driver: bridge

services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8301:8301"
      - "8500:8500"     # Web UI and API
      - "8600:8600/tcp" # DNS
      - "8600:8600/udp" # DNS
    networks:
      - monitoring
    command: agent -data-dir=/consul/data -config-dir=/consul/config -dev -client=0.0.0.0 -bind=0.0.0.0
    restart: unless-stopped

  zookeeper:
    image: zookeeper:3.8   
    container_name: zookeeper
    ports: 
      - "2181:2181"
    networks: 
      - monitoring 

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    volumes:
      - ./prometheus/etc:/etc/prometheus
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - consul

  clickhouse-base: &clickhouse
    image: clickhouse/clickhouse-server:24.4-alpine
    depends_on: [ zookeeper ]
    restart: unless-stopped
    networks:
      monitoring:
        aliases:
          - clickhouse 
    ports: []
    volumes:
      - ./clickhouse/config/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml:ro
      - ./clickhouse/config/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml:ro
      - ./clickhouse/config/users.xml:/etc/clickhouse-server/users.d/users.xml:ro

  # -------- SHARD 1 ----------
  clickhouse-1:
    <<: *clickhouse
    container_name: clickhouse-1
    hostname: clickhouse-1
    ports: [ "9001:9000", "8124:8123" ]
    volumes:
      - ./clickhouse/node01/macros.xml:/etc/clickhouse-server/config.d/macros.xml:ro
      - ./clickhouse/data/clickhouse-1:/var/lib/clickhouse
      - ./clickhouse/config/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml:ro
      - ./clickhouse/config/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/config/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml:ro

  clickhouse-2:
    <<: *clickhouse
    container_name: clickhouse-2
    hostname: clickhouse-2
    ports: [ "9002:9000", "8125:8123" ]
    volumes:
      - ./clickhouse/node02/macros.xml:/etc/clickhouse-server/config.d/macros.xml:ro
      - ./clickhouse/data/clickhouse-2:/var/lib/clickhouse
      - ./clickhouse/config/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml:ro
      - ./clickhouse/config/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/config/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml:ro

  # -------- SHARD 2 ----------
  clickhouse-3:
    <<: *clickhouse
    container_name: clickhouse-3
    hostname: clickhouse-3
    ports: [ "9003:9000", "8126:8123" ]
    volumes:
      - ./clickhouse/node03/macros.xml:/etc/clickhouse-server/config.d/macros.xml:ro
      - ./clickhouse/data/clickhouse-3:/var/lib/clickhouse
      - ./clickhouse/config/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml:ro
      - ./clickhouse/config/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/config/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml:ro

  clickhouse-4:
    <<: *clickhouse
    container_name: clickhouse-4
    hostname: clickhouse-4
    ports: [ "9004:9000", "8127:8123" ]
    volumes:
      - ./clickhouse/node04/macros.xml:/etc/clickhouse-server/config.d/macros.xml:ro
      - ./clickhouse/data/clickhouse-4:/var/lib/clickhouse
      - ./clickhouse/config/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml:ro
      - ./clickhouse/config/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/config/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml:ro
  
  grafana:
    image: grafana/grafana-oss:9.5.6
    container_name: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_LOG_LEVEL=error # убираем лишние логи
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - prometheus
      - clickhouse-1

  microservice:
    build: ./microservice
    environment:
      CLICKHOUSE_HOST: clickhouse-1
      CLICKHOUSE_PORT: "9000"
    expose:
      - "84"          
    networks:
      - monitoring
    depends_on:
      - clickhouse-1
      - consul
    deploy:
      replicas: 3
  
  ch-init:
    image: clickhouse/clickhouse-server:24.4-alpine
    networks:
      - monitoring
    depends_on:
      - clickhouse-1
    volumes:
      - ./microservice/ddl.sql:/ddl/ddl.sql:ro
    entrypoint:
      - /bin/sh
      - -c
      - |
        # ждём открытия порта 9000
        until clickhouse-client \
          --host clickhouse-1 \
          --user default \
          --password default \
          --query "SELECT 1"; do
          sleep 1
        done

        # применяем DDL
        clickhouse-client \
          --host clickhouse-1 \
          --user default \
          --password default \
          --multiquery < /ddl/ddl.sql
    restart: "no"

volumes:
  prometheus_data:
  grafana_data:
  clickhouse_data:
