{
 "title": "Статистика по загрузке товаров",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "grafana-clickhouse-datasource" },
   { "name": "company_id", "label": "CompanyID", "query": "0" }
  ]
 },
 "panels": [
  { "title": "Время товаров", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Время попытки создания товара за 30 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(date_create, INTERVAL 30 minute) at,\n    avg(attempt) AS \"среднее время\",\n    stddevPop(attempt) AS \"стандартное отклонение\",\n    \"среднее время\" + 3 * \"стандартное отклонение\" AS \"верхняя граница\"\nFROM\n    attempt_create_time\nWHERE\n    $__timeFilter(date_create)\ngroup by at"
    }
   ]
  },
  {
   "title": "Время попытки создания товара ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(date_create, INTERVAL 30 minute) at,\n    avg(attempt) AS \"среднее время\",\n    stddevPop(attempt) AS \"стандартное отклонение\",\n    \"среднее время\" + 3 * \"стандартное отклонение\" AS \"верхняя граница\"\nFROM\n    attempt_create_time\nWHERE\n    $__timeFilter(date_create)\ngroup by at"
    }
   ]
  },
  {
   "title": "Полное время создания товара за 30 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(date_create, INTERVAL 30 minute) at,\n    avg(full_time) AS \"среднее время\",\n    stddevPop(full_time) AS \"стандартное отклонение\",\n    \"среднее время\" + 3 * \"стандартное отклонение\" AS \"верхняя граница\"\nFROM\n    attempt_create_time\nWHERE\n    $__timeFilter(date_create) \ngroup by at"
    }
   ]
  },
  {
   "title": "Полное время создания товара ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(date_create, INTERVAL 30 minute) at,\n    avg(full_time) AS \"среднее время\",\n    stddevPop(full_time) AS \"стандартное отклонение\",\n    \"среднее время\" + 3 * \"стандартное отклонение\" AS \"верхняя граница\"\nFROM\n    attempt_create_time\nWHERE\n    $__timeFilter(date_create) \ngroup by at"
    },
    {
     "rawSql": "select\n    t0.newTS,\n    (t0.allItems-t0.tryFirst)/t2.items \"Товаров больше одной попытки\"\nfrom\n(Select\n    fromUnixTimestamp64Nano(csm.ts) newTS,\n    uniqMerge(first_time) tryFirst,\n    arraySum(mapValues(uniqMapMerge(csm.origins))) allItems\nfrom company_statistic_monthly csm\nwhere $__timeFilter(newTS)\ngroup by newTS) t0 left join (select\n newTS,\n sum(originRow.2) items\nfrom\n(select\n    toStartOfInterval(fromUnixTimestamp64Nano(ts), INTERVAL 1 day) newTS,\n    arrayJoin(uniqMapMerge(itemOrigins)) originRow\nfrom item_change_log_stat\nwhere\n    $__timeFilter(newTS)\ngroup by newTS) t\nwhere\n t.originRow.1 not like '%update/%'\ngroup by newTS) t2 on t0.newTS = t2.newTS\nwhere t0.newTS >= '2024-10-04'"
    }
   ]
  },
  {
   "title": "Процент товаров больше трех стандартных отклонений за 30 минут",
   "type": "timeseries",
   "description": "Процент товаров больше трех стандартных отклонений по времени попытки",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH\n    avg(attempt) AS mean_time,\n    stddevPop(attempt) AS stddev_time,\n    mean_time + 3 * stddev_time AS threshold\nSELECT\n    toStartOfInterval(date_create, INTERVAL 30 minute) at,\n    count(if(attempt > (SELECT mean_time + 3 * stddev_time FROM attempt_create_time where $__timeFilter(date_create)),1,null)) / count(*) * 100 \"товаров больше границы\"\nFROM\n    attempt_create_time\nWHERE\n    $__timeFilter(date_create)\ngroup by at"
    }
   ]
  },
  {
   "title": "Стабильность",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "WITH\n    quantileTiming(0.90)(cnt) AS avg_load_time\nSELECT\n    toStartOfInterval(hour, INTERVAL 30 minute ) at,\n    (avg_load_time / lagInFrame(avg_load_time) OVER (ORDER BY at) - 1) * -100 AS \"По количеству\"\nFROM (SELECT\n          toStartOfMinute(date_create) AS hour,\n          uniq(item_id) cnt\n      FROM\n          attempt_create_time\n      WHERE\n          $__timeFilter(date_create)\n        and is_created\n      Group by hour\n      ORDER BY\n          hour) t0\nGROUP BY at\nORDER BY at;"
    },
    {
     "rawSql": "WITH\n    avg(cnt) AS avg_load_time\nSELECT\n    toStartOfInterval(hour, INTERVAL 30 minute ) at,\n    (avg_load_time / lagInFrame(avg_load_time) OVER (ORDER BY at) - 1) * 100 AS \"По времени\"\nFROM (SELECT\n          toStartOfMinute(date_create) AS hour,\n          uniq(item_id) cnt\n      FROM\n          attempt_create_time\n      WHERE\n          $__timeFilter(date_create)\n        and is_created\n      Group by hour\n      ORDER BY\n          hour) t0\nGROUP BY at\nORDER BY at;"
    }
   ]
  },
  { "title": "Товаров", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Создание товаров в минуту со стандартным отклонением за 30 мин",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with\n  avg(cnt) as average_products,\n  stddevPop(cnt) AS standard_deviation,\n  average_products + 1 * standard_deviation AS upper_bound,\n  average_products - 1 * standard_deviation AS lower_bound_orig\nselect\n    toStartOfHour(hour) AS hour,\n    upper_bound \"верхняя граница\",\n    if(lower_bound_orig >= 0,  lower_bound_orig, 0) \"нижняя граница\"\nfrom\n    (SELECT\n        toStartOfMinute(date_create) AS hour,\n        uniq(item_id) cnt\n    FROM\n        attempt_create_time\n    WHERE\n        $__timeFilter(date_create)\n        and is_created\n    Group by hour\n    ORDER BY\n        hour) t0\nGroup by hour\nORDER BY\n    hour;"
    },
    {
     "rawSql": "SELECT\n        toStartOfMinute(date_create) AS at,\n        uniq(item_id) \"Товаров\"\n    FROM\n        attempt_create_time\n    WHERE\n        is_created\n    Group by at\n    ORDER BY\n        at"
    }
   ]
  },
  {
   "title": "Создание товаров в минуту по сегментам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n        toStartOfMinute(date_create) AS at,\n        if(country != 'RU', 'Глобал', 'РФ') as \"Сегмент\",\n        uniq(item_id) \"Товаров\"\n    FROM\n        attempt_create_time\n    WHERE\n        is_created\n    Group by at, \"Сегмент\"\n    ORDER BY\n        at, \"Сегмент\""
    }
   ]
  },
  {
   "title": "Процент созданных товаров с первой и более попыток ",
   "type": "timeseries",
   "description": "Учитываются только товары которые дошли до полки, упавшие товары не учитываются, см. график ниже по всем добавленным item   ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n    t0.newTS,\n    t0.tryFirst/t2.items \"С первой попытки\",\n    t0.allItems/t2.items \"Добавлено на полку\",\n    t0.tryFirst \"Количество с первой попытки\",\n    t0.allItems \"Количество добавленных на полку\"\nfrom\n(Select\n    fromUnixTimestamp64Nano(csm.ts) newTS,\n    uniqMerge(first_time) tryFirst,\n    arraySum(mapValues(uniqMapMerge(csm.origins))) allItems\nfrom company_statistic_monthly csm\nwhere $__timeFilter(newTS)\ngroup by newTS) t0 left join (select\n newTS,\n sum(originRow.2) items\nfrom\n(select\n    toStartOfInterval(fromUnixTimestamp64Nano(ts), INTERVAL 1 day) newTS,\n    arrayJoin(uniqMapMerge(itemOrigins)) originRow\nfrom item_change_log_stat\nwhere\n    $__timeFilter(newTS)\ngroup by newTS) t\nwhere\n t.originRow.1 not like '%update/%'\ngroup by newTS) t2 on t0.newTS = t2.newTS\nwhere t0.newTS >= '2024-10-04'"
    }
   ]
  },
  {
   "title": "Добавлено item за период",
   "type": "barchart",
   "description": "Количество добавленных новых item в разрезе дня",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n newTS,\n country \"Страна\", \n sum(originRow.2) \"Товаров\"\nfrom\n(select\n    toStartOfInterval(fromUnixTimestamp64Nano(ts), INTERVAL 1 day) newTS,\n    company_id,\n    country,\n    arrayJoin(uniqMapMerge(itemOrigins)) originRow\nfrom item_change_log_stat\nwhere\n    $__dateFilter(newTS)\ngroup by newTS, company_id, country) t\nwhere\n t.originRow.1 not like '%update/%'\ngroup by newTS, country\norder by newTS, country"
    }
   ]
  },
  {
   "title": "Процент по странам item",
   "type": "piechart",
   "description": "Количество добавленных новых item в разрезе дня",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n newTS,\n country \"Страна\", \n sum(originRow.2) \"Товаров\"\nfrom\n(select\n    toStartOfInterval(fromUnixTimestamp64Nano(ts), INTERVAL 1 day) newTS,\n    company_id,\n    country,\n    arrayJoin(uniqMapMerge(itemOrigins)) originRow\nfrom item_change_log_stat\nwhere\n    $__dateFilter(newTS)\ngroup by newTS, company_id, country) t\nwhere\n t.originRow.1 not like '%update/%'\ngroup by newTS, country\norder by newTS, country"
    }
   ]
  },
  {
   "title": "Загружено медиа файлов",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n    newTS,\n    media_type \"Тип медиа\",\n    sum(if(match(media_url, '.*?(ozone\\.ru|ozonusercontent\\.com)$'), cnt_media, 0)) \"Количество наших\",\n    sum(if(match(media_url, '.*?(ozone\\.ru|ozonusercontent\\.com|bad_hostname)$'), 0, cnt_media)) \"Количество внешних\",\n    sum(if(match(media_url, '.*?(bad_hostname)$'), cnt_media, 0)) \"Количество плохих ссылок\"\nfrom\n    (select\n    newTS,\n    splitByString(':', medias.1) media_array,\n    media_array[1] media_type,\n    media_array[2] media_url,\n    medias.2 cnt_media\n    from\n        (Select\n             fromUnixTimestamp64Nano(csm.ts) newTS,\n             arrayJoin(sumMapMerge(csm.media)) medias\n         from company_statistic_monthly csm\n         where newTS >= '2024-11-23'\n         group by newTS) t)\ngroup by newTS, media_type\norder by newTS, media_type;"
    }
   ]
  },
  {
   "title": "Статистика за сегодня с 00:00 UTC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 }
  },
  {
   "title": "Уникальных продавцов",
   "type": "stat",
   "description": "Уникальное количество продавцов загрузивших товаров, как обновление так и добавление",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    uniq(company_id)\n          from company_statistic_monthly\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day)"
    }
   ]
  },
  {
   "title": "Уникальных новых продавцов",
   "type": "stat",
   "description": "Новые продавцы",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    fromUnixTimestamp64Nano(ts) newTS,\n    uniq(company_id) \"Новых продавцов\"\nfrom\n    company_statistic_monthly\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day)\n    and company_id > (select max(company_id) from company_statistic_monthly where fromUnixTimestamp64Nano(ts) < toStartOfInterval(now(), interval 1 day))\ngroup by\n    newTS\norder by newTS"
    }
   ]
  },
  {
   "title": "Уникальных продавцов с первого раза",
   "type": "stat",
   "description": "Уникальных продавцов загрузивших товары с первого раза",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n uniq(company_id)\nfrom \n(select\n    company_id,\n    sum(c1) frst,\n    sum(arraySum(mapValues(c2))) al\nfrom (select\n          company_id,\n    uniqMerge(first_time) c1,\n      mapFilter((k, v) -> (k not like '%update/%'), uniqMapMerge(origins)) c2\n          from company_statistic_monthly\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day)\n    group by company_id) t0\ngroup by company_id\nhaving frst = al) t"
    }
   ]
  },
  {
   "title": "Уникальных продавцов \"потрачено\" ",
   "type": "stat",
   "description": "Уникальных продавцов не сумевших загрузить товары",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    uniq(company_id)\nfrom\n(select\n    company_id,\n    arraySum(mapValues(uniqMapMerge(tryItemOrigins))) c1,\n    arraySum(mapValues(uniqMapMerge(itemOrigins))) c2\nfrom item_change_log_stat\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day)\ngroup by company_id) t\nhaving c1 = c2;"
    }
   ]
  },
  {
   "title": "Попыток обновления добавленных товаров",
   "type": "stat",
   "description": "Сколько всего попыток обновить добавленные товары за день",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n sum(originRow.2)\nfrom\n(select\n    arrayJoin(mapSubtract(uniqMapMerge(origins),uniqMapMerge(tryOrigins))) originRow\nfrom item_change_log_stat\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day)) t\nwhere\n t.originRow.1 like '%update/%'"
    }
   ]
  },
  {
   "title": "Добавленных товаров обновлено",
   "type": "stat",
   "description": "Сколько всего обновили товаров дошедших до полки за сегодня",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n sum(originRow.2)\nfrom\n(select\n    arrayJoin(mapSubtract(uniqMapMerge(itemOrigins),uniqMapMerge(tryItemOrigins))) originRow\nfrom item_change_log_stat\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day)) t\nwhere\n t.originRow.1 like '%update/%'"
    }
   ]
  },
  {
   "title": "Попыток  добавления товаров",
   "type": "stat",
   "description": "Сколько всего попыток добавить товары за день",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n sum(originRow.2)\nfrom\n(select\n    arrayJoin(uniqMapMerge(tryOrigins)) originRow\nfrom item_change_log_stat\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day)) t"
    }
   ]
  },
  {
   "title": "Товаров добавляемых до полки",
   "type": "stat",
   "description": "Количество товаров которые пытаются добавить на полку, учитываются не только за текущий день, но и за предыдущие дни",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n sum(originRow.2)\nfrom\n(select\n    company_id,\n    arrayJoin(uniqMapMerge(tryItemOrigins)) originRow\nfrom item_change_log_stat\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day) group by company_id) t"
    }
   ]
  },
  {
   "title": "Попытки по источнику",
   "type": "piechart",
   "gridPos": { "h": 25, "w": 12, "x": 0, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n originRow.1 origin,\n sum(originRow.2)\nfrom\n(select\n    company_id,\n    arrayJoin(uniqMapMerge(origins)) originRow\nfrom item_change_log_stat\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day) group by company_id) t\n    group by origin"
    }
   ]
  },
  {
   "title": "Товаров по источнику",
   "type": "piechart",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n originRow.1 origin,\n sum(originRow.2)\nfrom\n(select\n    company_id,\n    arrayJoin(uniqMapMerge(itemOrigins)) originRow\nfrom item_change_log_stat\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day) group by company_id) t\n    group by origin"
    }
   ]
  },
  { "title": "Статистика по продовцам", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Уникальных продавцов",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  fromUnixTimestamp64Nano(ts) newTS,\n  uniq(company_id) \"Уникальных продавцов\"\nfrom \n  company_statistic_monthly\nwhere\n    $__dateFilter(newTS)\ngroup by\n  newTS\norder by newTS  "
    },
    {
     "rawSql": "select\n newTS,\n uniqIf(company_id, frst = al) \"Продавцов с первого раза\",\n uniqIf(company_id, frst = 0 ) \"Продавцов более одного раза\"\nfrom \n(select\n    newTS,\n    company_id,\n    sum(c1) frst,\n    sum(arraySum(mapValues(c2))) al\nfrom (select\n        fromUnixTimestamp64Nano(ts) newTS,\n        company_id,\n        uniqMerge(first_time) c1,\n        mapFilter((k, v) -> (k not like '%update/%'), uniqMapMerge(origins)) c2\n      from company_statistic_monthly\n      where\n        $__dateFilter(newTS)\n      group by newTS, company_id) t0\ngroup by newTS, company_id) t\ngroup by newTS"
    }
   ]
  },
  {
   "title": "Топ попыток продавцов",
   "type": "table",
   "description": "Показывает 10 самых загружаемых продавцов по попыткам (attempts)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "targets": [
    {
     "rawSql": "select\n    toDate(newTS) \"День\",\n    company_id \"Компания\",\n    attempts \"Попыток\",\n    originAttempts \"Попыток по источнику\"\n    from (\nselect\n    toStartOfInterval(fromUnixTimestamp64Nano(ts), INTERVAL 1 day) newTS,\n    company_id,\n    arraySum(mapValues(uniqMapMerge(origins))) attempts,\n    mapSort((k,v) -> -v,uniqMapMerge(origins)) originAttempts,\n    row_number() OVER (PARTITION BY newTS ORDER BY attempts DESC) AS rankAttempts\nfrom item_change_log_stat\ngroup by newTS, company_id) t\nWHERE $__dateFilter(t.newTS) and rankAttempts <= 10\norder by  t.newTS DESC, rankAttempts\nlimit 100"
    }
   ]
  },
  {
   "title": "Топ товаров продавцов",
   "type": "table",
   "description": "Показывает 10 самых загружаемых продавцов по товарам (items)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "targets": [
    {
     "rawSql": "select\n    toDate(newTS) \"День\",\n    company_id \"Компания\",\n    items \"Товаров\",\n    originItems \"Товаров по источнику\"\n    from (\nselect\n    toStartOfInterval(fromUnixTimestamp64Nano(ts), INTERVAL 1 day) newTS,\n    company_id,\n    arraySum(mapValues(uniqMapMerge(itemOrigins))) items,\n    mapSort((k,v) -> -v,uniqMapMerge(itemOrigins)) originItems,\n    row_number() OVER (PARTITION BY newTS ORDER BY items DESC) AS rankItems\nfrom item_change_log_stat\ngroup by newTS, company_id) t\nWHERE $__dateFilter(t.newTS) and rankItems <= 10\norder by  t.newTS DESC, rankItems\nlimit 100"
    }
   ]
  },
  {
   "title": "Загрузки по продавцу $company_id",
   "type": "table",
   "description": "Показывает количество попыток и товаров по источнику",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 132 },
   "targets": [
    {
     "rawSql": "select\n    fromUnixTimestamp64Nano(ts) At,\n    mapSort((k,v) -> -v,uniqMapMerge(origins)) \"Попыток по источникам\",\n    mapSort((k,v) -> -v,uniqMapMerge(itemOrigins)) \"Товаров по источникам\"\nfrom item_change_log_stat\nWHERE $__timeFilter(At) and company_id = ${company_id}\ngroup by At\norder by At desc"
    }
   ]
  },
  {
   "title": "Статистика загрузки по продавцам",
   "type": "timeseries",
   "description": "Где загрузок больше 15К или по компании",
   "gridPos": { "h": 33, "w": 24, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    tm,\n    toString(company_id) || ' (' || country || ')' AS seller_info,\n    sum(originRow.2) items\nFROM (select\n          fromUnixTimestamp64Nano(ts) AS tm,\n          company_id,\n          country,\n          arrayJoin(mapSubtract(uniqMapMerge(origins),uniqMapMerge(tryOrigins))) originRow\n      from item_change_log_stat\n      where\n          $__timeFilter(tm) and (company_id = ${company_id} or ${company_id} = 0)\n      group by tm, company_id, country) t\nGROUP BY\n    tm,\n    country,\n    company_id\nHAVING\n    (items > 15000 and ${company_id} = 0) or company_id = ${company_id}     \nORDER BY\n    tm,\n    country,\n    company_id\nlimit 500"
    }
   ]
  }
 ]
}