apiVersion: 1
datasources:
  - name: ClickHouse
    version: 1
    uid: adzva9wij30g0e
    type: grafana-clickhouse-datasource
    isDefault: true
    access: proxy
    url: tcp://clickhouse-1:9000
    jsonData:
      defaultDatabase: default
      tlsSkipVerify: true
      useNative: true
      maxOpenConns: 50
      maxIdleConns: 25
    secureJsonData:
      password: default
