apiVersion: 1
datasources:
  - name: grafana-clickhouse-ds
    type: grafana-clickhouse-datasource
    access: proxy
    orgId: 1
    jsonData:
      protocol: native
      defaultDatabase: item_upload
      host: clickhouse-1
      port: 9000
      maxOpenConns: 50
      maxIdleConns: 25
      connMaxLifetime: 300
    secureJsonData:
      username: default
      password: default
