{
 "title": "Статистика по загрузке товаров",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "grafana-clickhouse-datasource" },
   { "name": "company_id", "label": "CompanyID", "query": "0" }
  ]
 },
 "panels": [
  { "title": "Время товаров", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Время попытки создания товара за 30 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(date_create, INTERVAL 30 minute) at,\n    avg(attempt) AS \"среднее время\",\n    stddevPop(attempt) AS \"стандартное отклонение\",\n    \"среднее время\" + 3 * \"стандартное отклонение\" AS \"верхняя граница\"\nFROM\n    attempt_create_time_all\nWHERE\n    $__timeFilter(date_create)\ngroup by at"
    }
   ]
  },
  {
   "title": "Время попытки создания товара ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(date_create, INTERVAL 30 minute) at,\n    avg(attempt) AS \"среднее время\",\n    stddevPop(attempt) AS \"стандартное отклонение\",\n    \"среднее время\" + 3 * \"стандартное отклонение\" AS \"верхняя граница\"\nFROM\n    attempt_create_time_all\nWHERE\n    $__timeFilter(date_create)\ngroup by at"
    }
   ]
  },
  {
   "title": "Полное время создания товара за 30 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(date_create, INTERVAL 30 minute) at,\n    avg(full_time) AS \"среднее время\",\n    stddevPop(full_time) AS \"стандартное отклонение\",\n    \"среднее время\" + 3 * \"стандартное отклонение\" AS \"верхняя граница\"\nFROM\n    attempt_create_time_all\nWHERE\n    $__timeFilter(date_create) \ngroup by at"
    }
   ]
  },
  {
   "title": "Полное время создания товара ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(date_create, INTERVAL 30 minute) at,\n    avg(full_time) AS \"среднее время\",\n    stddevPop(full_time) AS \"стандартное отклонение\",\n    \"среднее время\" + 3 * \"стандартное отклонение\" AS \"верхняя граница\"\nFROM\n    attempt_create_time_all\nWHERE\n    $__timeFilter(date_create) \ngroup by at"
    },
    {
     "rawSql": "SELECT\n    t0.newTS,\n    (t0.allItems - t0.tryFirst) / t2.items AS \"Товаров больше одной попытки\"\nFROM\n(\n    SELECT\n        toStartOfInterval(fromUnixTimestamp64Nano(csd.ts), INTERVAL 1 day) AS newTS,\n        countDistinctIf(csd.item_id, cssd.is_created) AS tryFirst,\n        countDistinct(csd.item_id) AS allItems\n    FROM item_upload.company_statistic_daily_all AS csd\n    GLOBAL INNER JOIN item_upload.company_statistic_status_daily_all AS cssd\n        ON csd.item_id = cssd.item_id AND csd.ts = cssd.ts\n    WHERE fromUnixTimestamp64Nano(csd.ts) >= toStartOfInterval(now(), INTERVAL 1 day)\n    GROUP BY newTS\n) AS t0\nLEFT JOIN\n(\n    SELECT\n        newTS,\n        sum(originRow.2) AS items\n    FROM (\n        SELECT\n            toStartOfInterval(fromUnixTimestamp64Nano(ts), INTERVAL 1 day) AS newTS,\n            arrayJoin(uniqMapMerge(itemOrigins)) AS originRow\n        FROM item_upload.item_change_log_stat_all\n        WHERE fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), INTERVAL 1 day)\n        GROUP BY newTS\n    ) AS t\n    WHERE t.originRow.1 NOT LIKE '%update/%'\n    GROUP BY newTS\n) AS t2\nON t0.newTS = t2.newTS\n"
    }
   ]
  },
  {
   "title": "Процент товаров больше трех стандартных отклонений за 30 минут",
   "type": "timeseries",
   "description": "Процент товаров больше трех стандартных отклонений по времени попытки",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH\n    (\n        SELECT\n            avg(attempt) AS mean_time,\n            stddevPop(attempt) AS stddev_time\n        FROM attempt_create_time\n        WHERE $__timeFilter(date_create)\n    ) AS stats\n\nSELECT\n    toStartOfInterval(date_create, INTERVAL 30 minute) AS at,\n    countIf(attempt > (stats.mean_time + 3 * stats.stddev_time)) * 100.0 / count() AS \"товаров больше границы\"\nFROM attempt_create_time\nWHERE $__timeFilter(date_create)\nGROUP BY at\n"
    }
   ]
  },
  {
   "title": "Стабильность",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "WITH\n    quantileTiming(0.90)(cnt) AS avg_load_time\nSELECT\n    toStartOfInterval(hour, INTERVAL 30 minute ) at,\n    (avg_load_time / lagInFrame(avg_load_time) OVER (ORDER BY at) - 1) * -100 AS \"По количеству\"\nFROM (SELECT\n          toStartOfMinute(date_create) AS hour,\n          uniq(item_id) cnt\n      FROM\n          attempt_create_time_all\n      WHERE\n          $__timeFilter(date_create)\n        and is_created\n      Group by hour\n      ORDER BY\n          hour) t0\nGROUP BY at\nORDER BY at;"
    },
    {
     "rawSql": "WITH\n    avg(cnt) AS avg_load_time\nSELECT\n    toStartOfInterval(hour, INTERVAL 30 minute ) at,\n    (avg_load_time / lagInFrame(avg_load_time) OVER (ORDER BY at) - 1) * 100 AS \"По времени\"\nFROM (SELECT\n          toStartOfMinute(date_create) AS hour,\n          uniq(item_id) cnt\n      FROM\n          attempt_create_time_all\n      WHERE\n          $__timeFilter(date_create)\n        and is_created\n      Group by hour\n      ORDER BY\n          hour) t0\nGROUP BY at\nORDER BY at;"
    }
   ]
  },
  { "title": "Товаров", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Создание товаров в минуту со стандартным отклонением за 30 мин",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with\n  avg(cnt) as average_products,\n  stddevPop(cnt) AS standard_deviation,\n  average_products + 1 * standard_deviation AS upper_bound,\n  average_products - 1 * standard_deviation AS lower_bound_orig\nselect\n    toStartOfHour(hour) AS hour,\n    upper_bound \"верхняя граница\",\n    if(lower_bound_orig >= 0,  lower_bound_orig, 0) \"нижняя граница\"\nfrom\n    (SELECT\n        toStartOfMinute(date_create) AS hour,\n        uniq(item_id) cnt\n    FROM\n        attempt_create_time_all\n    WHERE\n        $__timeFilter(date_create)\n        and is_created\n    Group by hour\n    ORDER BY\n        hour) t0\nGroup by hour\nORDER BY\n    hour;"
    },
    {
     "rawSql": "SELECT\n        toStartOfMinute(date_create) AS at,\n        uniq(item_id) \"Товаров\"\n    FROM\n        attempt_create_time_all\n    WHERE\n        is_created\n    Group by at\n    ORDER BY\n        at"
    }
   ]
  },
  {
   "title": "Создание товаров в минуту по сегментам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n        toStartOfMinute(date_create) AS at,\n        if(country != 'RU', 'Глобал', 'РФ') as \"Сегмент\",\n        uniq(item_id) \"Товаров\"\n    FROM\n        attempt_create_time_all\n    WHERE\n        is_created\n    Group by at, \"Сегмент\"\n    ORDER BY\n        at, \"Сегмент\""
    }
   ]
  },
  {
   "title": "Процент созданных товаров с первой и более попыток ",
   "type": "timeseries",
   "description": "Учитываются только товары которые дошли до полки, упавшие товары не учитываются, см. график ниже по всем добавленным item   ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    t0.newTS,\n    t0.tryFirst / t2.items AS \"С первой попытки\",\n    t0.allItems / t2.items AS \"Добавлено на полку\",\n    t0.tryFirst AS \"Количество с первой попытки\",\n    t0.allItems AS \"Количество добавленных на полку\"\nFROM\n(\n    SELECT\n        toStartOfInterval(fromUnixTimestamp64Nano(csd.ts), INTERVAL 1 day) AS newTS,\n        uniqIf(csd.item_id, cssd.is_created) AS tryFirst,\n        countDistinct(csd.item_id) AS allItems\n    FROM item_upload.company_statistic_daily_all AS csd\n    GLOBAL INNER JOIN item_upload.company_statistic_status_daily_all AS cssd\n        ON csd.item_id = cssd.item_id AND csd.ts = cssd.ts\n    WHERE $__timeFilter(csd.ts)\n    GROUP BY newTS\n) AS t0\nLEFT JOIN\n(\n    SELECT\n        newTS,\n        sum(originRow.2) AS items\n    FROM\n    (\n        SELECT\n            toStartOfInterval(fromUnixTimestamp64Nano(ts), INTERVAL 1 day) AS newTS,\n            arrayJoin(uniqMapMerge(itemOrigins)) AS originRow\n        FROM item_upload.item_change_log_stat_all\n        WHERE $__timeFilter(ts)\n        GROUP BY newTS\n    ) AS t\n    WHERE t.originRow.1 NOT LIKE '%update/%'\n    GROUP BY newTS\n) AS t2\nON t0.newTS = t2.newTS\nWHERE t0.newTS >= toDateTime('2024-10-04')\n"
    }
   ]
  },
  {
   "title": "Добавлено item за период",
   "type": "barchart",
   "description": "Количество добавленных новых item в разрезе дня",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n newTS,\n country \"Страна\", \n sum(originRow.2) \"Товаров\"\nfrom\n(select\n    toStartOfInterval(fromUnixTimestamp64Nano(ts), INTERVAL 1 day) newTS,\n    company_id,\n    country,\n    arrayJoin(uniqMapMerge(itemOrigins)) originRow\nfrom item_change_log_stat_all\nwhere\n    $__dateFilter(newTS)\ngroup by newTS, company_id, country) t\nwhere\n t.originRow.1 not like '%update/%'\ngroup by newTS, country\norder by newTS, country"
    }
   ]
  },
  {
   "title": "Процент по странам item",
   "type": "piechart",
   "description": "Количество добавленных новых item в разрезе дня",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n newTS,\n country \"Страна\", \n sum(originRow.2) \"Товаров\"\nfrom\n(select\n    toStartOfInterval(fromUnixTimestamp64Nano(ts), INTERVAL 1 day) newTS,\n    company_id,\n    country,\n    arrayJoin(uniqMapMerge(itemOrigins)) originRow\nfrom item_change_log_stat_all\nwhere\n    $__dateFilter(newTS)\ngroup by newTS, company_id, country) t\nwhere\n t.originRow.1 not like '%update/%'\ngroup by newTS, country\norder by newTS, country"
    }
   ]
  },
  {
   "title": "Загружено медиа файлов",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    newTS,\n    media_type AS \"Тип медиа\",\n    sum(if(match(media_url, '.*?(ozone\\\\.ru|ozonusercontent\\\\.com)$'), cnt_media, 0)) AS \"Количество наших\",\n    sum(if(match(media_url, '.*?(ozone\\\\.ru|ozonusercontent\\\\.com|bad_hostname)$'), 0, cnt_media)) AS \"Количество внешних\",\n    sum(if(match(media_url, '.*?(bad_hostname)$'), cnt_media, 0)) AS \"Количество плохих ссылок\"\nFROM (\n    SELECT\n        fromUnixTimestamp64Nano(csm.ts) AS newTS,\n        splitByString(':', media_entry.1) AS media_array,\n        media_array[1] AS media_type,\n        media_entry.1 AS media_key,\n        media_entry.2 AS cnt_media,\n        replaceOne(media_entry.1, concat(media_array[1], ':'), '') AS media_url\n    FROM item_upload.company_statistic_daily_all AS csm\n    ARRAY JOIN url_by_media AS media_entry\n) t\nGROUP BY newTS, media_type\nORDER BY newTS, media_type\n"
    }
   ]
  },
  {
   "title": "Статистика за сегодня с 00:00 UTC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 }
  },
  {
   "title": "Уникальных продавцов",
   "type": "stat",
   "description": "Уникальное количество продавцов загрузивших товаров, как обновление так и добавление",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    uniq(company_id)\n          from company_statistic_daily_all\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day)"
    }
   ]
  },
  {
   "title": "Уникальных новых продавцов",
   "type": "stat",
   "description": "Новые продавцы",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    fromUnixTimestamp64Nano(ts) newTS,\n    uniq(company_id) \"Новых продавцов\"\nfrom\n    company_statistic_daily_all\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day)\n    and company_id > (select max(company_id) from company_statistic_daily_all where fromUnixTimestamp64Nano(ts) < toStartOfInterval(now(), interval 1 day))\ngroup by\n    newTS\norder by newTS"
    }
   ]
  },
  {
   "title": "Уникальных продавцов с первого раза",
   "type": "stat",
   "description": "Уникальных продавцов загрузивших товары с первого раза",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT uniq(company_id)\nFROM (\n    SELECT\n        csd.company_id,\n        uniqIf(csd.item_id, cssd.is_created) AS frst,\n        countIf(origin NOT LIKE '%update/%') AS al\n    FROM item_upload.company_statistic_daily_all AS csd\n    GLOBAL JOIN item_upload.company_statistic_status_daily_all AS cssd\n        ON csd.item_id = cssd.item_id AND csd.ts = cssd.ts\n    WHERE fromUnixTimestamp64Nano(csd.ts) >= toStartOfInterval(now(), INTERVAL 1 day)\n    GROUP BY csd.company_id\n    HAVING frst = al\n) t\n"
    }
   ]
  },
  {
   "title": "Уникальных продавцов \"потрачено\" ",
   "type": "stat",
   "description": "Уникальных продавцов не сумевших загрузить товары",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT uniq(company_id)\nFROM (\n    SELECT\n        company_id,\n        arraySum(mapValues(uniqMapMerge(tryItemOrigins))) AS c1,\n        arraySum(mapValues(uniqMapMerge(itemOrigins))) AS c2\n    FROM item_change_log_stat_all\n    WHERE fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), INTERVAL 1 day)\n    GROUP BY company_id\n    HAVING c1 = c2\n) t\n"
    }
   ]
  },
  {
   "title": "Попыток обновления добавленных товаров",
   "type": "stat",
   "description": "Сколько всего попыток обновить добавленные товары за день",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n sum(originRow.2)\nfrom\n(select\n    arrayJoin(mapSubtract(uniqMapMerge(origins),uniqMapMerge(itemOrigins))) originRow\nfrom item_change_log_stat_all\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day)) t\nwhere\n t.originRow.1 like '%update/%'"
    }
   ]
  },
  {
   "title": "Добавленных товаров обновлено",
   "type": "stat",
   "description": "Сколько всего обновили товаров дошедших до полки за сегодня",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    origin,\n    reinterpretAsInt64(sum(item_val)) - reinterpretAsInt64(sum(try_val)) AS diff\nFROM (\n    SELECT\n        originRow.1 AS origin,\n        originRow.2 AS item_val\n    FROM (\n        SELECT arrayJoin(uniqMapMerge(itemOrigins)) AS originRow\n        FROM item_upload.item_change_log_stat_all\n        WHERE fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), INTERVAL 1 day)\n    )\n) AS i\nFULL OUTER JOIN (\n    SELECT\n        originRow.1 AS origin,\n        originRow.2 AS try_val\n    FROM (\n        SELECT arrayJoin(uniqMapMerge(tryItemOrigins)) AS originRow\n        FROM item_upload.item_change_log_stat_all\n        WHERE fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), INTERVAL 1 day)\n    )\n) AS t\nUSING (origin)\nGROUP BY origin\nORDER BY diff DESC\n"
    }
   ]
  },
  {
   "title": "Попыток  добавления товаров",
   "type": "stat",
   "description": "Сколько всего попыток добавить товары за день",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n sum(originRow.2)\nfrom\n(select\n    arrayJoin(uniqMapMerge(itemOrigins)) originRow\nfrom item_change_log_stat_all\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day)) t"
    }
   ]
  },
  {
   "title": "Товаров добавляемых до полки",
   "type": "stat",
   "description": "Количество товаров которые пытаются добавить на полку, учитываются не только за текущий день, но и за предыдущие дни",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n sum(originRow.2)\nfrom\n(select\n    company_id,\n    arrayJoin(uniqMapMerge(tryItemOrigins)) originRow\nfrom item_change_log_stat_all\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day) group by company_id) t"
    }
   ]
  },
  {
   "title": "Попытки по источнику",
   "type": "piechart",
   "gridPos": { "h": 25, "w": 12, "x": 0, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n originRow.1 origin,\n sum(originRow.2)\nfrom\n(select\n    company_id,\n    arrayJoin(uniqMapMerge(origins)) originRow\nfrom item_change_log_stat_all\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day) group by company_id) t\n    group by origin"
    }
   ]
  },
  {
   "title": "Товаров по источнику",
   "type": "piechart",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n originRow.1 origin,\n sum(originRow.2)\nfrom\n(select\n    company_id,\n    arrayJoin(uniqMapMerge(itemOrigins)) originRow\nfrom item_change_log_stat_all\nwhere\n    fromUnixTimestamp64Nano(ts) >= toStartOfInterval(now(), interval 1 day) group by company_id) t\n    group by origin"
    }
   ]
  },
  { "title": "Статистика по продовцам", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Уникальных продавцов",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  fromUnixTimestamp64Nano(ts) newTS,\n  uniq(company_id) \"Уникальных продавцов\"\nfrom \n  company_statistic_daily_all\nwhere\n    $__dateFilter(newTS)\ngroup by\n  newTS\norder by newTS  "
    },
    {
     "rawSql": "SELECT\n    newTS,\n    uniqIf(company_id, items = 1) AS \"Продавцов с первой попытки\",\n    uniqIf(company_id, items > 1) AS \"Продавцов с более одной попытки\"\nFROM (\n    SELECT\n        toStartOfInterval(fromUnixTimestamp64Nano(ts), INTERVAL 1 day) AS newTS,\n        company_id,\n        countDistinctIf(item_id, origin NOT LIKE '%update/%') AS items\n    FROM item_upload.company_statistic_daily_all\n    WHERE $__timeFilter(ts)\n    GROUP BY newTS, company_id\n) AS t\nGROUP BY newTS\nORDER BY newTS\n"
    }
   ]
  },
  {
   "title": "Топ попыток продавцов",
   "type": "table",
   "description": "Показывает 10 самых загружаемых продавцов по попыткам (attempts)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "targets": [
    {
     "rawSql": "select\n    toDate(newTS) \"День\",\n    company_id \"Компания\",\n    attempts \"Попыток\",\n    originAttempts \"Попыток по источнику\"\n    from (\nselect\n    toStartOfInterval(fromUnixTimestamp64Nano(ts), INTERVAL 1 day) newTS,\n    company_id,\n    arraySum(mapValues(uniqMapMerge(origins))) attempts,\n    mapSort((k,v) -> -v,uniqMapMerge(origins)) originAttempts,\n    row_number() OVER (PARTITION BY newTS ORDER BY attempts DESC) AS rankAttempts\nfrom item_change_log_stat_all\ngroup by newTS, company_id) t\nWHERE $__dateFilter(t.newTS) and rankAttempts <= 10\norder by  t.newTS DESC, rankAttempts\nlimit 100"
    }
   ]
  },
  {
   "title": "Топ товаров продавцов",
   "type": "table",
   "description": "Показывает 10 самых загружаемых продавцов по товарам (items)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "targets": [
    {
     "rawSql": "select\n    toDate(newTS) \"День\",\n    company_id \"Компания\",\n    items \"Товаров\",\n    originItems \"Товаров по источнику\"\n    from (\nselect\n    toStartOfInterval(fromUnixTimestamp64Nano(ts), INTERVAL 1 day) newTS,\n    company_id,\n    arraySum(mapValues(uniqMapMerge(itemOrigins))) items,\n    mapSort((k,v) -> -v,uniqMapMerge(itemOrigins)) originItems,\n    row_number() OVER (PARTITION BY newTS ORDER BY items DESC) AS rankItems\nfrom item_change_log_stat_all\ngroup by newTS, company_id) t\nWHERE $__dateFilter(t.newTS) and rankItems <= 10\norder by  t.newTS DESC, rankItems\nlimit 100"
    }
   ]
  },
  {
   "title": "Загрузки по продавцу $company_id",
   "type": "table",
   "description": "Показывает количество попыток и товаров по источнику",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 132 },
   "targets": [
    {
     "rawSql": "select\n    fromUnixTimestamp64Nano(ts) At,\n    mapSort((k,v) -> -v,uniqMapMerge(origins)) \"Попыток по источникам\",\n    mapSort((k,v) -> -v,uniqMapMerge(itemOrigins)) \"Товаров по источникам\"\nfrom item_change_log_stat_all\nWHERE company_id = ${company_id}\ngroup by At\norder by At desc"
    }
   ]
  },
  {
   "title": "Статистика загрузки по продавцам",
   "type": "timeseries",
   "description": "Где загрузок больше 15К или по компании",
   "gridPos": { "h": 33, "w": 24, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    tm,\n    toString(company_id) || ' (' || country || ')' AS seller_info,\n    sum(originRow.2) items\nFROM (select\n          fromUnixTimestamp64Nano(ts) AS tm,\n          company_id,\n          country,\n          arrayJoin(mapSubtract(uniqMapMerge(origins),uniqMapMerge(itemOrigins))) originRow\n      from item_change_log_stat_all\n      where\n          $__timeFilter(tm) and (company_id = ${company_id} or ${company_id} = 0)\n      group by tm, company_id, country) t\nGROUP BY\n    tm,\n    country,\n    company_id\nHAVING\n    (items > 15000 and ${company_id} = 0) or company_id = ${company_id}     \nORDER BY\n    tm,\n    country,\n    company_id\nlimit 500"
    }
   ]
  }
 ]
}