global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "from-consul"
    consul_sd_configs:
      - server: "consul:8500"
        services: ["microservice"]    

    metrics_path: /metrics

    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: microservice
        action: keep
